### ISSUE TITLE
Comics?

### ISSUE THREAD

**Issue by woeterman94** [FluffyCookie000/garfield#1]
Did you stop running this script? Last commit was 5 days ago. Hope all is good

**Comment by FluffyCookie000** [comment]
Nah
On the pc I have running the script git isn't working properly its still running daily just it isn't committing the stuff to the repo automatically

**Comment by woeterman94** [comment]
Ah damn, it's just I miss the comics :( Op 14 jan. 2024 13:24 schreef FluffyCookie000 ***@***.***>:
Nah
On the pc I have running the script git isn't working properly its still running daily just it isn't committing the stuff to the repo automatically

**Comment by FluffyCookie000** [comment]
Well I'll try my best to commit them daily myself and figure out the issue with the pc soon. Also glad someone is looking at this!!
